default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: root
  host: 127.0.0.1
  port: 3307

development:
  <<: *default
  database: tuvantuyensinh

test:
  <<: *default
  database: tuvantuyensinh_test

production:
  adapter: mysql2
  encoding: utf8mb4
  pool: 5

  database: <%= ENV["MYSQLDATABASE"] %>
  username: <%= ENV["MYSQLUSER"] %>
  password: <%= ENV["MYSQLPASSWORD"] %>
  host: <%= ENV["MYSQLHOST"] %>
  port: <%= ENV["MYSQLPORT"] %>